name: antares_wallet
description: Antares Wallet flutter application.

publish_to: "none"

version: 0.0.7+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #business
  grpc: ^2.2.0
  protobuf: ^1.0.1
  stacked: ^1.6.0
  stacked_hooks: 0.1.1+3
  stacked_services: ^0.4.4+1
  meta: ^1.1.8
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.3
  equatable: ^1.2.0
  enum_to_string: ^1.0.9
  url_launcher: ^5.4.11
  clipboard_manager: ^0.0.4
  collection: ^1.14.12
  json_serializable: ^3.3.0

  auto_route:
  get_it:
  injectable:
  flutter_hooks:
  observable_ish:

  #fireabse
  firebase_analytics: ^5.0.15

  #blockchain
  bitcoin_flutter: ^2.0.1
  web3dart: ^1.2.3

  #ui
  cupertino_icons: ^0.1.3
  flutter_sparkline: ^0.1.0
  percent_indicator: ^2.1.5
  date_range_picker: ^1.0.6
  search_page: ^1.3.0
  image_picker: ^0.6.7+2
  chips_choice: ^1.2.0
  easy_localization: ^2.3.2
  syncfusion_flutter_charts: ^18.1.59

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/locales/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Proxima_Nova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Regular.otf
        - asset: assets/fonts/Proxima-Nova-Thin.otf
          weight: 100
        - asset: assets/fonts/Proxima-Nova-Light.otf
          weight: 300
        - asset: assets/fonts/Proxima-Nova-Semibold.otf
          weight: 700
        - asset: assets/fonts/Proxima-Nova-Bold.otf
          weight: 900
    - family: Akrobat
      fonts:
        - asset: assets/fonts/Akrobat-Bold.otf
          weight: 900
