name: antares_wallet
description: Antares Wallet flutter application.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #business
  stacked: ^1.5.2
  meta: ^1.1.8
  intl: ^0.16.1
  flutter_secure_storage: ^3.3.3
  get_it: ^4.0.2
  equatable: ^1.1.1
  enum_to_string: ^1.0.9
  url_launcher: ^5.4.7
  clipboard_manager: ^0.0.4

  #fireabse
  firebase_analytics: ^5.0.11

  #blockchain
  bitcoin_flutter: ^2.0.1
  web3dart: ^1.2.3

  #ui
  cupertino_icons: ^0.1.3
  webview_flutter: ^0.3.21
  percent_indicator: ^2.1.3
  modal_progress_hud: ^0.1.3

  #testing
  mockito: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/ru.json

  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/Proxima Nova Regular.otf
        - asset: assets/fonts/Proxima Nova Thin.otf
          weight: 100
        - asset: assets/fonts/Proxima Nova Light.otf
          weight: 300
        - asset: assets/fonts/Proxima Nova Semibold.otf
          weight: 700
        - asset: assets/fonts/Proxima Nova Bold.otf
          weight: 900
    - family: Akrobat
      fonts:
        - asset: assets/fonts/Akrobat-Bold.otf
          weight: 900
