name: sirius
description: SiriusWallet flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get_it: ^4.0.1
  bitcoin_flutter: ^2.0.0
  web3dart: ^1.2.3
  shared_preferences: ^0.5.7
  http: ^0.12.0+4
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/ru.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
