name: antares_wallet
description: Antares Wallet flutter application.

publish_to: "none"

version: 0.2.1+21

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #business
  get: ^3.8.0
  get_storage: ^1.3.0
  intl: ^0.16.1
  equatable: ^1.2.4
  grpc: ^2.2.0
  protobuf: ^1.0.1
  enum_to_string: ^1.0.9
  url_launcher: ^5.5.2
  clipboard_manager: ^0.0.4
  collection: ^1.14.13
  local_auth: ^0.6.3+1
  crypto: ^2.1.5
  package_info: ^0.4.3
  share: ^0.6.5
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  logger: ^0.9.2

  #fireabse
  firebase_analytics: ^6.0.0

  #blockchain
  bitcoin_flutter: ^2.0.1
  web3dart: ^1.2.3

  #ui
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  flutter_sparkline: ^0.1.0
  percent_indicator: ^2.1.5
  date_range_picker: ^1.0.6
  search_page: ^1.3.0
  image_picker: ^0.6.7+7
  chips_choice: ^1.2.0
  expandable: ^4.1.4
  pinput: ^0.2.5
  flutter_svg: ^0.18.1
  flutter_html: ^1.0.2
  webview_flutter: ^0.3.22+1
  transparent_image: ^1.0.0
  syncfusion_flutter_charts: ^18.2.56

  protoc_plugin: ^19.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Proxima_Nova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Regular.otf
        - asset: assets/fonts/Proxima-Nova-Thin.otf
          weight: 100
        - asset: assets/fonts/Proxima-Nova-Light.otf
          weight: 300
        - asset: assets/fonts/Proxima-Nova-Semibold.otf
          weight: 700
        - asset: assets/fonts/Proxima-Nova-Bold.otf
          weight: 900
    - family: Akrobat
      fonts:
        - asset: assets/fonts/Akrobat-Bold.otf
          weight: 900
