name: sirius
description: SiriusWallet flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #business
  meta: ^1.1.8
  flutter_secure_storage: ^3.3.3
  get_it: ^4.0.2
  equatable: ^1.1.1
  enum_to_string: ^1.0.9
  tuple: ^1.0.3
  url_launcher: ^5.4.7

  #blockchain
  bitcoin_flutter: ^2.0.0
  web3dart: ^1.2.3

  #ui
  cupertino_icons: ^0.1.3
  webview_flutter: ^0.3.21

  #testing
  mockito: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/ru.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
