name: antares_wallet
description: Antares Wallet flutter application.

publish_to: "none"

version: 0.3.2+32

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # getX state management
  get: ^3.21.3
  get_storage: ^1.3.2

  # grpc
  grpc: ^2.8.0
  protobuf: ^1.1.0
  protoc_plugin: ^19.2.0+1

  # crypto
  bitcoin_flutter: ^2.0.1
  crypto: ^2.1.5
  web3dart: ^1.2.3

  # utils and features
  intl: ^0.15.8
  equatable: ^1.2.5
  enum_to_string: ^1.0.9
  url_launcher: ^5.5.3
  clipboard_manager: ^0.0.4
  collection: ^1.14.13
  local_auth: ^0.6.3+1
  package_info: ^0.4.3
  share: ^0.6.5
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  flutter_money_formatter: ^0.8.3
  logger_flutter: ^0.7.1
  decimal: ^0.3.5
  string_validator: ^0.1.4

  # fireabse
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0+1

  # ui & animation
  google_fonts: ^1.1.1
  flutter_sparkline: ^0.1.0
  percent_indicator: ^2.1.6
  date_range_picker: ^1.0.6
  search_page: ^1.3.0
  image_picker: ^0.6.7+7
  chips_choice: ^1.2.0
  expandable: ^4.1.4
  flutter_svg: ^0.19.2+1
  webview_flutter: ^0.3.22+1
  transparent_image: ^1.0.0
  syncfusion_flutter_charts: ^18.3.51
  smooth_page_indicator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/fonts/
    - assets/images/
    - assets/images/onboarding/
